<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Intentroy"
     targetNamespace="http://oracle.com/sca/soapservice/soa_workshop/GetInventoryProv/Intentroy"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://oracle.com/sca/soapservice/soa_workshop/GetInventoryProv/Intentroy"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="InventoryEBS">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://oracle.com/sca/soapservice/soa_workshop/GetInventoryProv/Intentroy"
         location="oramds:/apps/FLEX/WSDL/Intentory.wsdl"/>
</wsdl:definitions>
