<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Intentroy"
     targetNamespace="http://oracle.com/sca/soapservice/soa_workshop/GetInventoryProv/Intentroy"
     xmlns:tns="http://oracle.com/sca/soapservice/soa_workshop/GetInventoryProv/Intentroy"
     xmlns:inp1="http://www.flexagon.com/ns/inventory"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.flexagon.com/ns/inventory" schemaLocation="oramds:/apps/FLEX/XSD/Inventory.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="input" element="inp1:ItemNumber"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="output" element="inp1:Inventory"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="GetInventory">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
