prompt --application/shared_components/reports/report_queries/customer_component_list
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(38002941296330782)
,p_name=>'CUSTOMER_COMPONENT_LIST'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- Query 1 use boat masster id 290344 for testing */',
'SELECT    br.brand_name',
'       || ''''''s Marine Product Resource Guide for  ''',
'       || bm.model_name',
'       || ''/''',
'       || bm.model_year',
'       || '' - Hull # ''',
'       || TO_CHAR (bm.hull_number)',
'           HDG1,',
'          --  ''/oracle/apps/apex/''',
'          --   || (SELECT LOWER (global_name) FROM global_name)',
'          ''/u01/app/oracle/Middleware/apex/images/BBG/''',
'       || TRIM (br.brand_code)',
'       || ''.bmp''',
'           p1_logo',
'  FROM qcis_boat_master bm, qcis_brand_master br',
' WHERE     bm.boat_master_id = :P454_BOAT_MASTER_ID',
'       AND br.qcis_brand_master_id = bm.brand_id',
'UNION',
'SELECT    br.brand_name',
'       || ''''''s Marine Product Resource Guide for  ''',
'       || bm.model_name',
'       || ''/''',
'       || bm.model_year',
'       || '' - Hull # ''',
'       || TO_CHAR (bm.hull_number)',
'           HDG1,',
'          --  ''/oracle/apps/apex/''',
'          --   || (SELECT LOWER (global_name) FROM global_name)',
'          ''/u01/app/oracle/Middleware/apex/images/BBG/''',
'       || TRIM (br.brand_code)',
'       || ''.bmp''',
'           p1_logo',
'  FROM qcis_boat_master_HIST bm, qcis_brand_master br',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND br.qcis_brand_master_id = bm.brand_id'))
,p_report_layout_id=>wwv_flow_api.id(38002745654329642)
,p_format=>'PDF'
,p_output_file_name=>'CUSTOMER_COMPONENT_LIST'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(38008684018632678)
,p_shared_query_id=>wwv_flow_api.id(38002941296330782)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- Query 1 use boat masster id 290344 for testing */',
'SELECT    br.brand_name',
'       || ''''''s Marine Product Resource Guide for  ''',
'       || bm.model_name',
'       || ''/''',
'       || bm.model_year',
'       || '' - Hull # ''',
'       || TO_CHAR (bm.hull_number)',
'           HDG1,',
'          --  ''/oracle/apps/apex/''',
'          --   || (SELECT LOWER (global_name) FROM global_name)',
'          ''/u01/app/oracle/Middleware/apex/images/BBG/''',
'       || TRIM (br.brand_code)',
'       || ''.bmp''',
'           p1_logo',
'  FROM qcis_boat_master bm, qcis_brand_master br',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND br.qcis_brand_master_id = bm.brand_id',
'UNION',
'SELECT    br.brand_name',
'       || ''''''s Marine Product Resource Guide for  ''',
'       || bm.model_name',
'       || ''/''',
'       || bm.model_year',
'       || '' - Hull # ''',
'       || TO_CHAR (bm.hull_number)',
'           HDG1,',
'          --  ''/oracle/apps/apex/''',
'          --   || (SELECT LOWER (global_name) FROM global_name)',
'          ''/u01/app/oracle/Middleware/apex/images/BBG/''',
'       || TRIM (br.brand_code)',
'       || ''.bmp''',
'           p1_logo',
'  FROM qcis_boat_master_HIST bm, qcis_brand_master br',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND br.qcis_brand_master_id = bm.brand_id'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(38008895626632678)
,p_shared_query_id=>wwv_flow_api.id(38002941296330782)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'	   ',
'/* query 2 */',
'SELECT (vde.element_name) description, ',
'       (vdd.variable_data_value) vd_value,',
'       (vdd.brand_value) product_brand,',
'       (vdd.model_value) product_model,',
'       vdd.comments comments',
'  FROM qcis_boat_master bm,',
'       qcis_brand_master br,',
'       qcis_inspection_header ih,',
'       qcis_var_data_detail vdd,',
'       qcis_var_data_elements vde',
' WHERE bm.boat_master_id = :P26_BOAT_MASTER_ID                          ',
'   AND ih.inspection_type = ''V''',
'   AND br.qcis_brand_master_id = bm.brand_id',
'   AND ih.plant_id = bm.plant_id',
'   AND ih.division_id = bm.division_id',
'   AND ih.brand_id = bm.brand_id',
'   AND ih.model_id = bm.model_id',
'   AND ih.hull_number = bm.hull_number',
'   AND vdd.header_id = ih.header_id',
'   AND vde.var_data_element_id = vdd.var_data_element_id',
'   AND vde.customer_share_flag = ''Y''',
'   AND NVL(vdd.replacement_flag,''N'') = ''N''',
'   AND DECODE(vdd.variable_data_value,NULL,0,1) = 1',
'UNION',
'SELECT (vde.element_name)        description,',
'       (vdd.variable_data_value) vd_value,',
'       (vdd.brand_value)         product_brand,',
'       (vdd.model_value)         product_model,',
'       vdd.comments              comments',
'  FROM qcis_boat_master_HIST        bm,',
'       qcis_brand_master            br,',
'       qcis_inspection_header_HIST  ih,',
'       qcis_var_data_detail_HIST    vdd,',
'       qcis_var_data_elements       vde,',
'       qcis_plant_master            pm',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND ih.inspection_type = ''V''',
'       AND br.qcis_brand_master_id = bm.brand_id',
'       AND ih.plant_id = bm.plant_id',
'       AND ih.division_id = bm.division_id',
'       AND ih.brand_id = bm.brand_id',
'       AND ih.model_id = bm.model_id',
'       AND ih.hull_number = bm.hull_number',
'       AND vdd.header_id = ih.header_id',
'       AND vde.var_data_element_id = vdd.var_data_element_id',
'       AND vde.customer_share_flag = ''Y''',
'       AND NVL (vdd.replacement_flag, ''N'') = ''N''',
'       AND DECODE (vdd.variable_data_value, NULL, 0, 1) = 1'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(38009077387632678)
,p_shared_query_id=>wwv_flow_api.id(38002941296330782)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* query 3 */',
'SELECT NVL (SUM (NVL (LENGTH (vdd.brand_value), 0)), 0) product_brand,',
'       NVL (SUM (NVL (LENGTH (vdd.model_value), 0)), 0) product_model,',
'       NVL (SUM (NVL (LENGTH (vdd.comments), 0)), 0)    comments',
'  FROM qcis_boat_master        bm,',
'       qcis_brand_master       br,',
'       qcis_inspection_header  ih,',
'       qcis_var_data_detail    vdd,',
'       qcis_var_data_elements  vde',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND ih.inspection_type = ''V''',
'       AND br.qcis_brand_master_id = bm.brand_id',
'       AND ih.plant_id = bm.plant_id',
'       AND ih.division_id = bm.division_id',
'       AND ih.brand_id = bm.brand_id',
'       AND ih.model_id = bm.model_id',
'       AND ih.hull_number = bm.hull_number',
'       AND vdd.header_id = ih.header_id',
'       AND vde.var_data_element_id = vdd.var_data_element_id',
'       AND vde.customer_share_flag = ''Y''',
'       AND NVL (vdd.replacement_flag, ''N'') = ''N''',
'       AND DECODE (vdd.variable_data_value, NULL, 0, 1) = 1',
'UNION',
'SELECT NVL (SUM (NVL (LENGTH (vdd.brand_value), 0)), 0) product_brand,',
'       NVL (SUM (NVL (LENGTH (vdd.model_value), 0)), 0) product_model,',
'       NVL (SUM (NVL (LENGTH (vdd.comments), 0)), 0)    comments',
'  FROM qcis_boat_master_HIST        bm,',
'       qcis_brand_master            br,',
'       qcis_inspection_header_HIST  ih,',
'       qcis_var_data_detail_HIST    vdd,',
'       qcis_var_data_elements       vde',
' WHERE     bm.boat_master_id = :P26_BOAT_MASTER_ID',
'       AND ih.inspection_type = ''V''',
'       AND br.qcis_brand_master_id = bm.brand_id',
'       AND ih.plant_id = bm.plant_id',
'       AND ih.division_id = bm.division_id',
'       AND ih.brand_id = bm.brand_id',
'       AND ih.model_id = bm.model_id',
'       AND ih.hull_number = bm.hull_number',
'       AND vdd.header_id = ih.header_id',
'       AND vde.var_data_element_id = vdd.var_data_element_id',
'       AND vde.customer_share_flag = ''Y''',
'       AND NVL (vdd.replacement_flag, ''N'') = ''N''',
'       AND DECODE (vdd.variable_data_value, NULL, 0, 1) = 1'))
);
end;
/
